name = cannons
title = Cannons
depends = default, bucket
optional_depends = mesecons, locks, moreores, tnt
description = """
Adds cannons to Minetest Game.
To shoot, insert munitions and gunpowder and punch the cannon with a torch.
The projectiles can destroy nodes and hurt players.
"""
